#!/bin/sh
MYDIR="$(dirname $(readlink -f $0))"
export WEBKIT_EXEC_PATH="${MYDIR}/bin"
export WEBKIT_INJECTED_BUNDLE_PATH="${MYDIR}/lib"
export WEBKIT_INSPECTOR_RESOURCES_PATH="${MYDIR}/share"
export LD_LIBRARY_PATH="${MYDIR}/lib:${MYDIR}/sys/lib"
exec "${MYDIR}/bin/WPEWebDriver" "$@"
